name: cartisan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_native_splash: ^2.2.19
  get_storage: ^2.1.1
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.4
  google_fonts: ^4.0.3
  surf_lint_rules: ^2.1.0
  animate_do: ^3.0.2
  image_picker: ^0.8.7+1
  dotted_line: ^3.1.0
  lottie: ^2.3.2
  flutter_staggered_grid_view: ^0.4.0
  flutter_staggered_animations: ^1.1.1
  fluttertoast: ^8.2.1
  progress_dialog_null_safe: ^1.0.7
  firebase_core: ^2.9.0
  firebase_auth:
  cloud_firestore:
  firebase_messaging:
  firebase_storage:
  cloud_functions:
  dio: ^5.1.2
  awesome_notifications:
  paginated_list: ^1.0.3
  infinite_scroll_pagination: ^3.2.0
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_native_splash:
  image: assets/icons/splashLogo.png
  color: "000000"
  fullscreen: true

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

