// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvYPPjf56vOOfrOS_1HNZL0RVGXvGerS4',
    appId: '1:75477652308:web:ac30492603dda63489aec1',
    messagingSenderId: '75477652308',
    projectId: 'cloud-function-practice-f911f',
    authDomain: 'cloud-function-practice-f911f.firebaseapp.com',
    storageBucket: 'cloud-function-practice-f911f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoSzpuz-VzFNCbvwiw5RB09tYV-AjaNLo',
    appId: '1:75477652308:android:26bb96586a8d9a5a89aec1',
    messagingSenderId: '75477652308',
    projectId: 'cloud-function-practice-f911f',
    storageBucket: 'cloud-function-practice-f911f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvmjgB8B527AhrnY7nlZNmQ0nPi5-hy7I',
    appId: '1:75477652308:ios:e1891fd0753550bc89aec1',
    messagingSenderId: '75477652308',
    projectId: 'cloud-function-practice-f911f',
    storageBucket: 'cloud-function-practice-f911f.appspot.com',
    iosClientId:
        '75477652308-1oauugaeoebdhkp41qs1kbeer2gb69f5.apps.googleusercontent.com',
    iosBundleId: 'com.cartisan.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvmjgB8B527AhrnY7nlZNmQ0nPi5-hy7I',
    appId: '1:75477652308:ios:e1891fd0753550bc89aec1',
    messagingSenderId: '75477652308',
    projectId: 'cloud-function-practice-f911f',
    storageBucket: 'cloud-function-practice-f911f.appspot.com',
    iosClientId:
        '75477652308-1oauugaeoebdhkp41qs1kbeer2gb69f5.apps.googleusercontent.com',
    iosBundleId: 'com.cartisan.app',
  );
}
